#!/bin/bash

[ -e dag-example && rm -rf origin ]
mkdir origin
pushd origin

git init

echo "C1" > file
git add file
git commit -m "C1 commit"
git branch work_br


echo "C2" > file
git add file
git commit -m "C2 commit"

echo "C3" > file
git add file
git commit -m "C3 commit"

git checkout work_br

echo "C4" > file
git add file
git commit -m "C4 commit"

echo "C5" > file
git add file
git commit -m "C5 commit"

git checkout master
git tag "V1.0" -m "The V1.0 release"

popd

git clone origin local
pushd origin

git merge work_br
echo "C6" > file
git add file
git commit -m "C6 commit, merge"

popd

pushd local

git fetch
git log origin/master work_br --graph

git checkout work_br

git checkout work_br
echo "C7" > file
git add file
git commit -m "C7 commit"

echo "NOTE: the master branch fails, since we didn't update it"
echo "      to the current origin/master tracking branch"
echo "      git push origin work_br:work_br would have only pushed work_br"
git push origin

popd

pushd origin

git log master work_br --graph
